# Generated by Django 4.2.7 on 2025-01-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_airquality"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AirQuality",
        ),
    ]
