# Generated by Django 4.2.7 on 2024-12-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="disease",
            field=models.CharField(default="unspecified", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="region",
            field=models.CharField(default="unknown", max_length=100),
        ),
    ]
