# Generated by Django 4.2.7 on 2024-12-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_product_description_remove_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="disease",
            field=models.CharField(default="unspecified", max_length=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="region",
            field=models.CharField(default="unknown", max_length=10),
        ),
    ]
