# Generated by Django 4.2.7 on 2024-12-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_product_disease_alter_product_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="disease",
            field=models.CharField(default="unspecified", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="region",
            field=models.CharField(default="unknown", max_length=100),
        ),
    ]
