# Generated by Django 4.2.7 on 2024-12-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_product_disease_alter_product_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="region_detail",
            field=models.CharField(default="-", max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="disease",
            field=models.CharField(default="-", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="region",
            field=models.CharField(default="-", max_length=100),
        ),
    ]
