# Generated by Django 5.1.4 on 2024-12-11 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_column='USER_ID', max_length=16)),
                ('password', models.CharField(db_column='PASSWORD', max_length=64)),
                ('email', models.CharField(db_column='EMAIL', max_length=40)),
                ('nickname', models.CharField(db_column='NICKNAME', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.users')),
                ('region', models.CharField(blank=True, db_column='REGION', max_length=16, null=True)),
                ('diseases', models.CharField(blank=True, db_column='DISEASES', max_length=100, null=True)),
            ],
            options={
                'db_table': 'info',
                'managed': True,
            },
        ),
    ]
