# Generated by Django 5.1.4 on 2024-12-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, db_column='EMAIL', max_length=40, null=True),
        ),
    ]
